# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provision_install_vboxguestadditions.sh"
  #config.vm.provision "shell", path: "provision_install_ansible_pip.sh"
  #config.vm.provision "shell", path: "provision_install_pip_modules.sh"
  #config.vm.provision "shell", path: "provision_install_terraform.sh"
  config.vm.provision "shell", path: "provision_cleanup.sh"
  
  #config.vm.provision "shell", inline: "reboot"

  # Rsync https://www.vagrantup.com/docs/synced-folders/rsync.html
  # rsync used because vboxsf was not working

  #config.vm.synced_folder "../.", "/gcp", mount_options: ["dmode=775,fmode=777"], type: "rsync",  rsync__auto: true,
  #  rsync__exclude: ".git/",
  #  rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "-z"]
  
end
